import header from "./Header.js";
import headerMobile from "./HeaderMobile.js";
import heroSection from "./HeroSection.js";
import heroMobile from "./HeroMobile.js";
import mostPopular from "./MostPopular.js";
import devices from "./Devices.js";
import devicesMobile from "./DevicesMobile.js";
import TV from "./TV.js";
import free from "./Free.js";
import freeMobile from "./FreeMobile.js";
import kids from "./Kids.js";
import kidsMobile from "./KidsMobile.js";
import cinema from "./Cinema.js";
import cinemaMobile from "./CinemaMobile.js";
import comments from "./Comments.js";
import FAQ from "./FAQ.js";
import filimo from "./Filimo.js";
import footer from "./Footer.js";
import watchLaterMobile from "./WatchLaterMobile.js";
import buyFilimo from "./BuyFilimo.js";


header();
headerMobile();
heroSection();
heroMobile();
mostPopular();
devices();
devicesMobile();
TV();
free();
freeMobile();
kids();
kidsMobile();
cinema();
cinemaMobile();
comments();
FAQ();
filimo();
footer();
watchLaterMobile();
buyFilimo();
